apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-cloud-api  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-cloud-api
  template:
    metadata:
      labels:
        app: library-cloud-api
    spec:
      containers:
      - name: library-cloud-api
        image: gcr.io/my-k8s-project-300415/library-cloud-api:1.0        
        env:
        - name: "PORT"
          value: "8080"

---

apiVersion: v1
kind: Service
metadata:
  name: library-cloud-api  
spec:
  type: LoadBalancer
  selector:
    app: library-cloud-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080