apiVersion: v1
kind: Service
metadata:
  name: library-cloud-api
  namespace: default
spec:
  selector:
    app: library-cloud-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  
  
  
  